### PR TITLE
Move from spray REST go gRPC

### PR DESCRIPTION
**Pull request by parkan**

### CODE REVIEW

**Comment by parkan** [comment]
@yusefnapora @bigs ready for review here

**Comment by parkan** [comment]
Ahh this still hangs on exit, need to fix shutdown

**Comment by yusefnapora** [comment]
for some reason I'm having trouble setting up a venv and running this... will try again tomorrow :)

**Comment by parkan** [comment]
@yusefnapora see instructions here https://github.com/mediachain/mediachain-cli/blob/ak-grpc/README.md

**Comment by yusefnapora** [comment]
@parkan I keep getting a compilation error trying when `python ./setup.py install` tries to build the grpcio package: 

```
src/core/compression/compression_algorithm.c:130:28: error: conflicting types for 'grpc_compression_algorithm_for_level'
grpc_compression_algorithm grpc_compression_algorithm_for_level(
                           ^
/usr/local/include/grpc/compression.h:62:36: note: previous declaration is here
GRPCAPI grpc_compression_algorithm grpc_compression_algorithm_for_level(
```

This is after installing grpc from source as described in the readme (which seems to be where the previous declaration is coming from...)

I'll mess about some more and see if I can sort it out

**Comment by yusefnapora** [comment]
sorry, I didn't read the readme correctly :)

should be doing `pip install .` instead

**Comment by yusefnapora** [comment]
now it installs, but I get `ImportError: No module named rpc` when trying to run.  The generated files are in `mediachain/rpc`, but there's no `__init__.py` in that dir... could that be why?

**Comment by yusefnapora** [comment]
creating an empty `mediachain/rpc/__init__.py` and reinstalling worked; now I can run and get the help text.  maybe add `touch mediachain/rpc/__init__.py` to the hook script?

**Comment by yusefnapora** [comment]
or probably better to just add the empty `__init__.py` to the repo

**Comment by parkan** [comment]
oh blah I think I forgot to add init to git, good catch

**Comment by parkan** [comment]
@yusefnapora try it now

**Comment by yusefnapora** [comment]
👍

**Pull request merged**
